name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build V
      run: |
        git clone --depth 1 https://github.com/vlang/v ../v
        cd ../v
        make
        cd ../vast
    - name: Build example
      run: |
        time ../v/v run . example/demo.v
    - name: Results
      run: ls -lart example/*
    - name: demo.json
      run: cat example/demo.json

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build V
      run: |
        git clone --depth 1 https://github.com/vlang/v ../v
        cd ../v
        make
        cd ../vast
    - name: Build example
      run: |
        time ../v/v run . example/demo.v
    - name: Results
      run: ls -lart example/*
    - name: demo.json
      run: cat example/demo.json

  windows-msvc:
    runs-on: windows-latest
    env:
        VFLAGS: -cc msvc
    steps:
    - uses: actions/checkout@v1
    - name: Build V
      run: |
        git clone --depth 1 https://github.com/vlang/v ..\v
        cd ..\v
        .\make.bat -msvc
        cd ..\vast
    - name: Build example
      run: |
        ..\v\v.exe run . example\demo.v
    - name: Results
      run: dir example\
    - name: demo.json
      run: type example\demo.json
